# This workflow runs on pushes to main
# any merge/push to main will result in development being deployed

name: Build and deploy development for release

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.gitignore'
      
    branches:
      - main

jobs:
  deploy-development:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Compile USWDS assets
        working-directory: ./src
        run: |
          docker compose run node npm install npm@latest &&
          docker compose run node npm install &&
          docker compose run node npx gulp copyAssets &&
          docker compose run node npx gulp compile
      - name: Collect static assets 
        working-directory: ./src
        run: docker compose run app python manage.py collectstatic --no-input
      - name: Deploy to cloud.gov sandbox
        uses: 18f/cg-deploy-action@main
        env:
          DEPLOY_NOW: thanks
        with:
          cf_username: ${{ secrets.CF_DEVELOPMENT_USERNAME }}
          cf_password: ${{ secrets.CF_DEVELOPMENT_PASSWORD }}
          cf_org: cisa-dotgov
          cf_space: development
          push_arguments: "-f ops/manifests/manifest-development.yaml"
      - name: Run Django migrations
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_username: ${{ secrets.CF_DEVELOPMENT_USERNAME }}
          cf_password: ${{ secrets.CF_DEVELOPMENT_PASSWORD }}
          cf_org: cisa-dotgov
          cf_space: development
          cf_command: "run-task getgov-development --command 'python manage.py migrate' --name migrate"